# Generated by Django 6.1.1 on 2026-09-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
