# Generated by Django 6.1.1 on 2026-09-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
