# Generated by Django 6.1.1 on 2026-09-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0005_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
