# Generated by Django 6.1.1 on 2026-09-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0007_alter_order_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
