# Generated by Django 6.1.1 on 2026-09-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0008_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer')], max_length=10),
        ),
    ]
