# Generated by Django 6.1.1 on 2026-09-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0014_registrationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
